---
title: "data_wrangling2"
output: html_document
date: "2025-10-09"
---

```{r setup}
library(tidyverse)
library(rvest)
library(httr)

```


```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)

drug_use_html

```

## an easy case

```{r}
ndsuh_df = 
  drug_use_html |>
  html_table() |>
  first() |>
  slice(-1)

```



## get the html

```{r}
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")

```

## pull out elements of the html that i care about

```{r}
title_vec = 
  swm_html |>
  html_elements(".ipc-title-link-wrapper .ipc-title__text") |>
  html_text()

metascore_vec = 
  swm_html |>
  html_elements(".metacritic-score-box") |>
  html_text()

runtime_vec = 
  swm_html |>
  html_elements(".dli-title-metadata-item:nth-child(2)") |>
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    score = metascore_vec,
    runtime = runtime_vec)

```


## APIs

get data using API

get the nyc water consumption dataset

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") |> 
  content("parsed") 

nyc_water|>
  ggplot(aes(x= year, y = nyc_consumption_million_gallons_per_day))+
  geom_point()

```

Access BRFSS

```{r}
brfss_df = 
  GET(
    "https://chronicdata.cdc.gov/api/v3.views.acme-vg9e/query.csv",
    query = list("app_token" = "xxx")
  ) |>
  content("parsed")


```


Look at Pokemon data

```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/ditto") |>
  content()

poke[[4]]
```