---
title: "viz_3"
output: html_document
date: "2025-10-02"
---

```{r}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

Import the weather data

```{r}
data("weather_df")

weather_df =
  weather_df |>
  mutate(month = floor_date(date, unit = "month")) 
# 将date列中的每个日期向下舍入到当月的第一天，原先的日期另存一列

```

Make plots

```{r}

weather_df =
  ggplot(aes(x = prcp)) +
  geom_histogram()


```

Check on extreme values

```{r}
weather_df |>
  filter(prcp > 1000)

```


Look at data again.

```{r}
weather_df |>
  filter(tmax >= 20, tmax <= 30)|>
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name))+
  geom_point

```


```{r}
weather_df |>
  group_by(name, month)

```

Group and count things

```{r}
weather_df |>
  group_by(name) |>
  summarize(
    n = n() #how many observations
  )

```


```{r}
weather_df |>
  group_by(name) |>
  summarize(
    n = n_distinct(date) #how many distinct observations
  )

```

You can count directly

```{r}
weather_df |>
  count(name)

```

```{r}
weather_df |>
  group_by(name, month) |>
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    mean_prec = mean(prcp, na.rm = TRUE),
    median_tmax = median(tmax),
    sd_tmax = sd(tmax))


```



```{r}
weather_df |>
  group_by(name, month) |>
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    ) |>
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_line()




```

```{r}
weather_df |>
  group_by(name, month) |>
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    ) |>
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) |>
  kniter::kable(digits = 2)

```

## mutate with groups

```{r}
weather_df |>
  group_by(name) |>
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    center_tmax = tmax - mean_tmax
    ) |>
  ggplot(aes(x = date, y = center_tmax, color = name)) +
  geom_point()

```

Look for cold days.

```{r}
weather_df |>
  group_by(name, month) |>
  mutate(temp_rank = min_rank(desc(tmin))) |>
  filter(temp_rank < 2)


```


what about lags? #获取前一行的数据

```{r}
weather_df |>
  group_by(name)|>
  mutate(lagged_tmax = lag(tmax)) |>
  view()

```

Use the variables you create

```{r}
weather_df |>
  group_by(name)|>
  mutate(
    temp_change = tmax - lag(tmax)
    ) |>
  summarize(
    sd_max_change = sd(temp_change, na.rm = TRUE),
    tmax_change_max = max(temp_change, na.rm = TRUE)
  )


```

```{r}
pulse_df |>
  ggplot(aes(x=visit, y=bdi))+
  geom_boxplot()


pulse_df|>
  group_by(visit)|>
  summarize(
    mean_bdi = mean(bdi, na.rm = TRUE),
    median_bdi = median(bdi, na.rm = TRUE)
  )|>
  knitr::kable(digits = 2)

```


